- .github/workflows/dotnet.yml
- Refugee.Core.Api.Infrastructure.Build/Program.cs
- Refugee.Core.Api.Infrastructure.Build/Refugee.Core.Api.Infrastructure.Build.csproj
- Refugee.Core.Api/Controllers/HomeController.cs
- Refugee.Core.Api/Startup.cs
- Refugee.Core.sln
> INFRA: Initialize Build Pipelines

- Refugee.Core.Api.Tests.Unit/DeleteMe.cs
- Refugee.Core.Api.Tests.Unit/Refugee.Core.Api.Tests.Unit.csproj
- Refugee.Core.sln
> INFRA: Initialize Unit Tests Project

- Refugee.Core.Api/Models/Enums/Pets.cs
> DATA: Add Pets Enum

- Refugee.Core.Api/Models/Enums/Gender.cs
- Refugee.Core.Api/Models/Refugees/Refugee.cs
> DATA: Add Refugee Model

- RefugeeLand.Core.Api/Brokers/Loggings/ILoggingBroker.cs
- RefugeeLand.Core.Api/Brokers/Loggings/LoggingBroker.cs
- RefugeeLand.Core.Api/Startup.cs
> BROKERS: Add Logging

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.Refugees.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.Refugees.cs
- RefugeeLand.Core.Api/Models/Refugees/Refugee.cs
@mabroukmahdhi @Spectralgo  please, have a look
> CODE RUB: Clean Up

- RefugeeLand.Core.Api/Controllers/RefugeesController.cs
> CONTROLLERS: Post Refugee

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.Shelters.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.Shelters.cs
> BROKERS: Insert Shelter

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.Hosts.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.Hosts.cs
@ElbekDeveloper I squashed it to make it pretty like you want 😄
> BROKERS: Insert Host

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.Shelters.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.Shelters.cs
> BROKERS: Select All Shelters

- RefugeeLand.Core.Api.Infrastructure.Provision/RefugeeLand.Core.Api.Infrastructure.Provision.csproj
- RefugeeLand.Core.Api.Tests.Unit/Foundations/RefugeeServiceTests.Validations.Add.cs
- RefugeeLand.Core.Api.Tests.Unit/Foundations/RefugeeServiceTests.cs
- RefugeeLand.Core.Api.Tests.Unit/RefugeeLand.Core.Api.Tests.Unit.csproj
- RefugeeLand.Core.Api/RefugeeLand.Core.Api.csproj
> CODE RUB: Upgrade to New Xeption Standard

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.Shelters.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.Shelters.cs
> BROKERS: Select Shelter By Id

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.RefugeeGroups.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.RefugeeGroups.cs
> BROKERS: Insert RefugeeGroup

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.RefugeeGroups.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.RefugeeGroups.cs
> BROKERS: Select All RefugeeGroups

- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Exceptions.RetreieveAll.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Logic.RetrieveAll.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Refugees/RefugeeServiceTests.Logic.RetrieveAll.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/IRefugeeGroupService.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/RefugeeGroupService.Exceptions.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/RefugeeGroupService.cs
- RefugeeLand.Core.Api/Startup.cs
> FOUNDATIONS: Retrieve All RefugeeGroups

- RefugeeLand.Core.Api.Tests.Unit/RefugeeLand.Core.Api.Tests.Unit.csproj
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Exceptions.Add.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Exceptions.RetrieveAll.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Logic.Add.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Logic.RetrieveAll.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Validations.Add.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/AlreadyExistsHostException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/FailedHostServiceException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/FailedHostStorageException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostDependencyException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostDependencyValidationException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostServiceException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostValidationException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/InvalidHostException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/InvalidHostReferenceException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/NullHostException.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/HostService.Exceptions.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/HostService.Validations.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/HostService.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/IHostService.cs
> FOUNDATIONS: Host Service - Retrieve All Hosts

- RefugeeLand.Core.Api.Tests.Unit/RefugeeLand.Core.Api.Tests.Unit.csproj
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Exceptions.Add.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Logic.Add.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.Validations.Add.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/Hosts/HostServiceTests.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/AlreadyExistsHostException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/FailedHostServiceException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/FailedHostStorageException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostDependencyException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostDependencyValidationException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostServiceException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/HostValidationException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/InvalidHostException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/InvalidHostReferenceException.cs
- RefugeeLand.Core.Api/Models/Hosts/Exceptions/NullHostException.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/HostService.Exceptions.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/HostService.Validations.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/HostService.cs
- RefugeeLand.Core.Api/Services/Foundations/Hosts/IHostService.cs
> FOUNDATIONS: Host Service - Add Host

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.Shelters.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.Shelters.cs
> BROKERS: Delete Shelter

- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.Shelters.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.Shelters.cs
> BROKERS: Update Shelter

- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Validation.Modify.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/RefugeeGroupService.Validations.cs
@Spectralgo Take it from here <3
> FOUNDATIONS: RefugeeGroup Service - Modify RefugeeGroup 

- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Exceptions.Modify.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Logic.Modify.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Logic.RetrieveById.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Validation.Modify.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.Validations.RetrieveById.cs
- RefugeeLand.Core.Api.Tests.Unit/Services/Foundations/RefugeeGroups/RefugeeGroupServiceTests.cs
- RefugeeLand.Core.Api/Brokers/Storages/IStorageBroker.RefugeeGroups.cs
- RefugeeLand.Core.Api/Brokers/Storages/StorageBroker.RefugeeGroups.cs
- RefugeeLand.Core.Api/Controllers/RefugeeGroupsController.cs
- RefugeeLand.Core.Api/Controllers/ShelterRequestsController.cs
- RefugeeLand.Core.Api/Models/RefugeeGroups/Exceptions/LockedRefugeeGroupException.cs
- RefugeeLand.Core.Api/Models/RefugeeGroups/Exceptions/NotFoundRefugeeGroupException.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/IRefugeeGroupService.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/RefugeeGroupService.Exceptions.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/RefugeeGroupService.Validations.cs
- RefugeeLand.Core.Api/Services/Foundations/RefugeeGroups/RefugeeGroupService.cs
@Sharaf-Mansour take it from here
> FOUNDATIONS: RefugeeGroup Service - Modify RefugeeGroup
